$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2.0

$script:Result = [ordered]@{schemaVersion='1.0.0';kind='LimitHaloAgentResult';action='Unknown';status='FAILED_SAFE';code='INTERNAL_FAILURE';trust='NOT_EVALUATED';recommended='NONE';performed='NONE';candidateId=$null;setupSha256=$null;helperSha256=$null;acceptance=$null;installedState='UNSAFE';rollbackState='NOT_CHECKED';changed=$false;launched=$false;settingsAccess='NOT_READ';authenticationPerformed=$false}

function Complete-Result([string]$Status,[string]$Code,[int]$ExitCode) {
  $script:Result.status=$Status; $script:Result.code=$Code
  $json=$script:Result|ConvertTo-Json -Compress -Depth 5
  if ([Text.Encoding]::UTF8.GetByteCount($json)-gt 16384 -or $json-match'[\x00-\x08\x0B\x0C\x0E-\x1F]' -or $json-match'(?i)(?:[A-Z]:\\\\|\\\\\\\\|/users/|https?://|[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})') {
    $json='{"schemaVersion":"1.0.0","kind":"LimitHaloAgentResult","action":"Unknown","status":"FAILED_SAFE","code":"OUTPUT_REJECTED","trust":"NOT_EVALUATED","recommended":"NONE","performed":"NONE","candidateId":null,"setupSha256":null,"helperSha256":null,"acceptance":null,"installedState":"UNSAFE","rollbackState":"NOT_CHECKED","changed":false,"launched":false,"settingsAccess":"NOT_READ","authenticationPerformed":false}';$ExitCode=30
  }
  [Console]::Out.WriteLine($json);exit $ExitCode
}
function Fail([string]$Code,[int]$ExitCode){if($ExitCode-eq10){Complete-Result 'ACTION_REQUIRED' $Code 10};if($ExitCode-eq20){Complete-Result 'INVALID_OR_UNSAFE' $Code 20};Complete-Result 'FAILED_SAFE' $Code 30}
function Sha([string]$Path){$s=[IO.File]::OpenRead($Path);$h=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($h.ComputeHash($s))).Replace('-','').ToLowerInvariant()}finally{$h.Dispose();$s.Dispose()}}
function Is-Reparse([string]$Path){if(-not(Test-Path -LiteralPath $Path)){return $false};return((Get-Item -Force -LiteralPath $Path).Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0}
function Safe-Chain([string]$Path){$p=[IO.Path]::GetFullPath($Path);while(-not(Test-Path -LiteralPath $p)){$n=[IO.Path]::GetDirectoryName($p);if([string]::IsNullOrWhiteSpace($n)-or$n-eq$p){throw 'PATH_UNSAFE'};$p=$n};while(-not[string]::IsNullOrWhiteSpace($p)){if(Is-Reparse $p){throw 'PATH_UNSAFE'};$n=[IO.Path]::GetDirectoryName($p);if([string]::IsNullOrWhiteSpace($n)-or$n-eq$p){break};$p=$n}}
function Read-Json ([string]$Path,[int]$Max){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)-or(Is-Reparse $Path)){throw 'BUNDLE_INVALID'};$i=Get-Item -LiteralPath $Path;if($i.Length-lt2-or$i.Length-gt$Max){throw 'BUNDLE_INVALID'};try{return Get-Content -Raw -Encoding UTF8 -LiteralPath $Path|ConvertFrom-Json}catch{throw 'BUNDLE_INVALID'}}
function Exact($Object,[string[]]$Names,[string]$Code){if($null-eq$Object){throw$Code};$a=@($Object.PSObject.Properties.Name);if($a.Count-ne$Names.Count){throw$Code};foreach($n in $Names){if(-not($a-ccontains$n)){throw$Code}}}
function Parse-Args([object[]]$Values){$v=@($Values);if($v.Count-ne1-and$v.Count-ne3){throw 'INVALID_ARGUMENTS'};$a=[string]$v[0];if(-not(@('Auto','Status','Install','Repair')-ccontains$a)){throw 'INVALID_ACTION'};$x=$null;if($v.Count-eq3){if([string]$v[1]-cne'-AcceptUnsignedExact'){throw 'INVALID_ARGUMENTS'};$x=[string]$v[2];if($x-cnotmatch'^(?:[0-9a-f]{64}:){2}[0-9a-f]{64}$'){throw 'INVALID_ACCEPTANCE'}};return [pscustomobject]@{Action=$a;Acceptance=$x}}
function Context {
  $b=[IO.Path]::GetFullPath($PSScriptRoot).TrimEnd('\');Safe-Chain $b;$f=[Environment]::GetEnvironmentVariable('LIMIT_HALO_AGENT_FIXTURE_ROOT');$t=[Environment]::GetEnvironmentVariable('LIMIT_HALO_TEST_ROOT')
  if([string]::IsNullOrWhiteSpace($f)-and[string]::IsNullOrWhiteSpace($t)){$l=$env:LOCALAPPDATA;$r=$env:APPDATA;if([string]::IsNullOrWhiteSpace($l)-or[string]::IsNullOrWhiteSpace($r)){throw 'ENVIRONMENT_UNAVAILABLE'};$product=Join-Path $l 'Programs\AILimitsWidget';$programs=Join-Path $r 'Microsoft\Windows\Start Menu\Programs';Safe-Chain $product;Safe-Chain $programs;return [pscustomobject]@{Fixture=$false;Bundle=$b;Root=$null;Product=$product;Programs=$programs}}
  if([string]::IsNullOrWhiteSpace($f)-or[string]::IsNullOrWhiteSpace($t)){throw 'FIXTURE_INVALID'};$t=[IO.Path]::GetFullPath($t).TrimEnd('\');$f=[IO.Path]::GetFullPath($f).TrimEnd('\');if(-not$f.StartsWith($t+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'FIXTURE_INVALID'};Safe-Chain $t;Safe-Chain $f;$c=Read-Json (Join-Path $f 'limit-halo-agent-fixture-v1.json' ) 1024;Exact $c @('schemaVersion','kind') 'FIXTURE_INVALID';if($c.schemaVersion-cne'1.0.0'-or$c.kind-cne'LimitHaloAgentFixture'){throw 'FIXTURE_INVALID'};if(-not$b.StartsWith($f+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'FIXTURE_INVALID'};return [pscustomobject]@{Fixture=$true;Bundle=$b;Root=$f;Product=Join-Path $f 'installed\AILimitsWidget';Programs=Join-Path $f 'programs'}
}
function Bundle($C){
  $mp=Join-Path $C.Bundle 'release-manifest.json';$sp=Join-Path $C.Bundle 'SHA256SUMS.txt';$hp=Join-Path $C.Bundle 'LimitHalo-Agent.ps1';if([IO.Path]::GetFullPath($PSCommandPath)-cne[IO.Path]::GetFullPath($hp)){throw 'HELPER_LOCATION_INVALID'};$m=Read-Json $mp 131072
  Exact $m @('schemaVersion','kind','internalProductId','displayName','displayNameStatus','version','architecture','candidateId','sourceIdentity','signature','automaticUpdater','hostedGitHubActionsObserved','publicationPerformed','payloadManifestSha256','dependencyLicenseManifestSha256','dependencyInventory','buildInputs','artifacts') 'MANIFEST_INVALID'
  if($m.schemaVersion-cne'1.0.0'-or$m.kind-cne'release-bundle'-or$m.internalProductId-cne'AILimitsWidget'-or$m.architecture-cne'x64'-or[string]$m.candidateId-cnotmatch'^[0-9a-f]{64}$'-or$m.automaticUpdater-ne$false-or$m.publicationPerformed-ne$false){throw 'MANIFEST_INVALID'};Exact $m.signature @('status','verifiedSigner','statement') 'MANIFEST_INVALID';if($m.signature.status-cne'unsigned'-or$null-ne$m.signature.verifiedSigner){throw 'SIGNED_PATH_UNSUPPORTED'}
  $mapi=@{};$arts=@($m.artifacts);if($arts.Count-ne3){throw 'MANIFEST_INVALID'};foreach($e in $arts){Exact $e @('path','size','sha256') 'MANIFEST_INVALID';$n=[string]$e.path;if([IO.Path]::GetFileName($n)-cne$n-or$mapi.ContainsKey($n)-or[string]$e.sha256-cnotmatch'^[0-9a-f]{64}$'){throw 'MANIFEST_INVALID'};$mapi[$n]=$e};$setups=@($mapi.Keys|?{$_-cmatch'^LimitHalo-[0-9]+\.[0-9]+\.[0-9]+-Setup\.exe$'});$zips=@($mapi.Keys|?{$_-cmatch'^LimitHalo-[0-9]+\.[0-9]+\.[0-9]+-Windows-x64\.zip$'});if($setups.Count-ne1-or$zips.Count-ne1-or-not$mapi.ContainsKey('LimitHalo-Agent.ps1')){throw 'MANIFEST_INVALID'}
  $si=Get-Item -LiteralPath $sp -ErrorAction Stop;if((Is-Reparse $sp)-or$si.Length-gt4096){throw 'CHECKSUMS_INVALID'};$sums=@{};foreach($line in @(Get-Content -Encoding ASCII -LiteralPath $sp)){if($line-cnotmatch'^([0-9a-f]{64})  ([^/\\]+)$'-or$sums.ContainsKey($Matches[2])){throw 'CHECKSUMS_INVALID'};$sums[$Matches[2]]=$Matches[1]};$names=@($setups[0],$zips[0],'LimitHalo-Agent.ps1','release-manifest.json');if($sums.Count-ne4){throw 'CHECKSUMS_INVALID'};foreach($n in $names){if(-not$sums.ContainsKey($n)){throw 'CHECKSUMS_INVALID'}}
  foreach($n in @($setups[0],$zips[0],'LimitHalo-Agent.ps1')){$p=Join-Path $C.Bundle $n;if(-not(Test-Path -LiteralPath $p -PathType Leaf)-or(Is-Reparse $p)){throw 'ARTIFACT_MISMATCH'};$i=Get-Item -LiteralPath $p;$d=Sha $p;if($i.Length-ne[int64]$mapi[$n].size-or$d-cne[string]$mapi[$n].sha256-or$d-cne[string]$sums[$n]){throw 'ARTIFACT_MISMATCH'}};if((Sha $mp)-cne[string]$sums['release-manifest.json']){throw 'CHECKSUMS_INVALID'}
  if(-not$C.Fixture){$ss=Get-AuthenticodeSignature -LiteralPath (Join-Path $C.Bundle $setups[0]);$hs=Get-AuthenticodeSignature -LiteralPath $hp;if($ss.Status.ToString()-cne'NotSigned'-or$hs.Status.ToString()-cne'NotSigned'){throw 'SIGNED_PATH_UNSUPPORTED'}}
  return [pscustomobject]@{Setup=Join-Path $C.Bundle $setups[0];CandidateId=[string]$m.candidateId;SetupSha256=[string]$mapi[$setups[0]].sha256;HelperSha256=[string]$mapi['LimitHalo-Agent.ps1'].sha256}
}
function Marker([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)-or(Is-Reparse $Path)){return $null};if((Get-Item -LiteralPath $Path).Length-gt66){return $null};$v=(Get-Content -Raw -Encoding ASCII -LiteralPath $Path).Trim();if($v-cnotmatch'^[0-9a-f]{64}$'){return $null};return $v}
function Candidate([string]$Product,[string]$Id,[bool]$Fixture){
  $root=Join-Path (Join-Path $Product 'versions')$Id;if(-not(Test-Path -LiteralPath $root -PathType Container)-or(Is-Reparse $root)){return 'UNSAFE'};try{foreach($d in @(Get-ChildItem -LiteralPath $root -Recurse -Directory -Force)){if(($d.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){return 'UNSAFE'}};$m=Read-Json (Join-Path $root 'package-manifest.json' ) 262144;Exact $m @('schemaVersion','kind','internalProductId','displayName','displayNameStatus','version','architecture','candidateId','sourceIdentity','signatureStatus','brokerSha256','files') 'CANDIDATE_UNSAFE';if($m.schemaVersion-cne'1.0.0'-or$m.kind-cne'installed-payload'-or$m.internalProductId-cne'AILimitsWidget'-or$m.candidateId-cne$Id){return 'UNSAFE'};$decl=New-Object 'Collections.Generic.HashSet[string]' ([StringComparer]::OrdinalIgnoreCase);$bad=$false;foreach($e in @($m.files)){Exact $e @('path','size','sha256') 'CANDIDATE_UNSAFE';$r=[string]$e.path;if([string]::IsNullOrWhiteSpace($r)-or$r.Contains('\')-or$r.StartsWith('/')-or@($r.Split('/')|?{$_ -in @('','.','..')}).Count-ne0-or-not$decl.Add($r)-or[string]$e.sha256-cnotmatch'^[0-9a-f]{64}$'){return 'UNSAFE'};$p=Join-Path $root $r;if(-not(Test-Path -LiteralPath $p -PathType Leaf)-or(Is-Reparse $p)){$bad=$true;continue};$i=Get-Item -LiteralPath $p;if($i.Length-ne[int64]$e.size-or(Sha $p)-cne[string]$e.sha256){$bad=$true}};$actual=New-Object 'Collections.Generic.HashSet[string]' ([StringComparer]::OrdinalIgnoreCase);foreach($i in @(Get-ChildItem -LiteralPath $root -Recurse -File -Force)){if(($i.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){return 'UNSAFE'};$r=$i.FullName.Substring($root.Length).TrimStart('\').Replace('\','/');if($r-cne'package-manifest.json'){[void]$actual.Add($r)}};foreach($r in $actual){if(-not$decl.Contains($r)){return 'UNSAFE'}};if($bad-or-not$actual.SetEquals($decl)){return 'DAMAGED'};if(-not$Fixture){$exe=Join-Path $root 'AILimitsWidget.exe';$p=Start-Process -FilePath $exe -ArgumentList @('--health-check','--offline','--no-provider-start') -WorkingDirectory $root -WindowStyle Hidden -Wait -PassThru;if($p.ExitCode-ne0){return 'DAMAGED'}};return 'HEALTHY'}catch{return 'UNSAFE'}
}
function Process-State($C,[string]$Exe){if($C.Fixture){$p=Join-Path $C.Root 'process-state.txt';if(-not(Test-Path -LiteralPath $p)){return 'NONE'};$v=(Get-Content -Raw -Encoding ASCII -LiteralPath $p).Trim();if(@('NONE','OWNED','FOREIGN')-cnotcontains$v){return 'FOREIGN'};return $v};$count=0;foreach($p in @(Get-Process -Name 'AILimitsWidget' -ErrorAction SilentlyContinue)){try{$x=$p.MainModule.FileName}catch{return 'FOREIGN'};if(-not[IO.Path]::GetFullPath($x).Equals([IO.Path]::GetFullPath($Exe),[StringComparison]::OrdinalIgnoreCase)){return 'FOREIGN'};$count++};if($count-gt1){return 'FOREIGN'};if($count-eq1){return 'OWNED'};return 'NONE'}
function Shortcut-State($C,[string]$Exe){
  if($C.Fixture){$p=Join-Path $C.Root 'shortcut-state.txt';if((Test-Path -LiteralPath $p)-and(Get-Content -Raw -LiteralPath $p).Trim()-ceq'FOREIGN'){return 'FOREIGN'};return 'OK'}
  $wd=[IO.Path]::GetDirectoryName($Exe);foreach($r in @('LimitHalo.lnk','Configure LimitHalo.lnk','Startup\LimitHalo.lnk')){$p=Join-Path $C.Programs $r;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){continue};if(Is-Reparse $p){return 'FOREIGN'};$s=$null;$l=$null;try{$s=New-Object -ComObject WScript.Shell;$l=$s.CreateShortcut($p);$args=([string]$l.Arguments).Trim();$expected=if($r-ceq'Configure LimitHalo.lnk'){'--configure'}elseif($r-ceq'Startup\LimitHalo.lnk'){'STARTUP'}else{''};if(-not[IO.Path]::GetFullPath([string]$l.TargetPath).Equals([IO.Path]::GetFullPath($Exe),[StringComparison]::OrdinalIgnoreCase)){return 'FOREIGN'};if(-not[IO.Path]::GetFullPath([string]$l.WorkingDirectory).Equals($wd,[StringComparison]::OrdinalIgnoreCase)){return 'FOREIGN'};if(($expected-ceq'STARTUP'-and@('','--startup')-cnotcontains$args)-or($expected-cne'STARTUP'-and$args-cne$expected)){return 'FOREIGN'}}catch{return 'FOREIGN'}finally{if($null-ne$l){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($l)};if($null-ne$s){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($s)}}};return 'OK'
}
function Installed($C){if(-not(Test-Path -LiteralPath $C.Product)){return [pscustomobject]@{State='ABSENT';Active=$null;Rollback='ABSENT';RollbackId=$null;Executable=$null;Process='NONE'}};if(-not(Test-Path -LiteralPath $C.Product -PathType Container)-or(Is-Reparse $C.Product)){throw 'INSTALLED_STATE_UNSAFE'};$a=Marker(Join-Path $C.Product 'active-candidate.txt');if($null-eq$a){throw 'MARKER_INVALID'};$cs=Candidate $C.Product $a $C.Fixture;if($cs-ceq'UNSAFE'){throw 'INSTALLED_STATE_UNSAFE'};$exe=Join-Path (Join-Path (Join-Path $C.Product 'versions')$a)'AILimitsWidget.exe';$ps=Process-State $C $exe;if($ps-ceq'FOREIGN'){throw 'FOREIGN_PROCESS'};if((Shortcut-State $C $exe)-ceq'FOREIGN'){throw 'FOREIGN_SHORTCUT'};$rs='ABSENT';$r=$null;$rp=Join-Path $C.Product 'rollback-candidate.txt';if(Test-Path -LiteralPath $rp){$r=Marker $rp;if($null-eq$r-or(Candidate $C.Product $r $C.Fixture)-cne'HEALTHY'){$rs='UNSAFE'}else{$rs='HEALTHY'}};if($cs-ceq'DAMAGED'){$state='DAMAGED_OWNED'}elseif($ps-ceq'OWNED'){$state='HEALTHY_RUNNING'}else{$state='HEALTHY_STOPPED'};return [pscustomobject]@{State=$state;Active=$a;Rollback=$rs;RollbackId=$r;Executable=$exe;Process=$ps}}
function Recommend([string]$Action,$I,[string]$Candidate){if($Action-ceq'Status'){return 'NONE'};if($Action-ceq'Auto'){if($I.State-ceq'ABSENT'){return 'INSTALL'};if($I.State-ceq'DAMAGED_OWNED'){return 'REPAIR'};if($I.Active-cne$Candidate){return 'INSTALL'};if($I.State-ceq'HEALTHY_STOPPED'){return 'LAUNCH'};return 'NONE'};if($Action-ceq'Install'){if($I.State-ceq'DAMAGED_OWNED'){throw 'USE_REPAIR'};if($I.State-cne'ABSENT'-and$I.Active-ceq$Candidate){return 'NONE'};return 'INSTALL'};if($I.State-ceq'ABSENT'){throw 'NOT_INSTALLED'};if($I.State-ceq'DAMAGED_OWNED'){return 'REPAIR'};return 'NONE'}
function Stop-OwnedOnce($C,$I){
  if($I.Process-cne'OWNED'){return}
  if($C.Fixture){
    $mode='GRACEFUL';$modePath=Join-Path $C.Root 'stop-mode.txt';if(Test-Path -LiteralPath $modePath){$mode=(Get-Content -Raw -LiteralPath $modePath).Trim()}
    if(@('GRACEFUL','FORCE','REPLACED','FOREIGN','FAILURE','LOCKED','MULTIPLE_PROCESS','INACCESSIBLE_MODULE','KILL_FAIL','SECOND_KILL')-cnotcontains$mode){throw 'FIXTURE_INVALID'}
    if($mode-ceq'MULTIPLE_PROCESS'){throw 'OWNED_PROCESS_BUSY'}
    if($mode-ceq'INACCESSIBLE_MODULE'){throw 'OWNED_PROCESS_BUSY'}
    $events=Join-Path $C.Root 'stop-events.txt';[IO.File]::WriteAllText($events,"CLOSE`n",[Text.Encoding]::ASCII)
    if($mode-ceq'GRACEFUL'){[IO.File]::WriteAllText((Join-Path $C.Root 'process-state.txt'),"NONE`n",[Text.Encoding]::ASCII);return}
    if($mode-ceq'FAILURE'-or$mode-ceq'LOCKED'){throw 'OWNED_PROCESS_BUSY'}
    [IO.File]::AppendAllText($events,"REVALIDATE`n",[Text.Encoding]::ASCII)
    if($mode-ceq'REPLACED'){throw 'OWNED_PROCESS_BUSY'}
    if($mode-ceq'FOREIGN'){throw 'FOREIGN_PROCESS'}
    [IO.File]::AppendAllText($events,"KILL`n",[Text.Encoding]::ASCII)
    if($mode-ceq'KILL_FAIL'-or$mode-ceq'SECOND_KILL'){throw 'OWNED_PROCESS_BUSY'}
    [IO.File]::WriteAllText((Join-Path $C.Root 'process-state.txt'),"NONE`n",[Text.Encoding]::ASCII);return
  }
  $found=@(Get-Process -Name 'AILimitsWidget' -ErrorAction SilentlyContinue);if($found.Count-ne1){throw 'OWNED_PROCESS_BUSY'};$p=$found[0]
  try{$path=$p.MainModule.FileName;$pidValue=$p.Id;$started=$p.StartTime.ToUniversalTime().Ticks}catch{throw 'OWNED_PROCESS_BUSY'}
  if(-not[IO.Path]::GetFullPath($path).Equals([IO.Path]::GetFullPath($I.Executable),[StringComparison]::OrdinalIgnoreCase)){throw 'FOREIGN_PROCESS'}
  try{[void]$p.CloseMainWindow();if($p.WaitForExit(2000)){return}}catch{throw 'OWNED_PROCESS_BUSY'}
  try{$same=[Diagnostics.Process]::GetProcessById($pidValue)}catch{return}
  try{$samePath=$same.MainModule.FileName;$sameStarted=$same.StartTime.ToUniversalTime().Ticks}catch{$same.Dispose();throw 'OWNED_PROCESS_BUSY'}
  if($same.Id-ne$pidValue-or$sameStarted-ne$started){$same.Dispose();throw 'OWNED_PROCESS_BUSY'}
  if(-not[IO.Path]::GetFullPath($samePath).Equals([IO.Path]::GetFullPath($I.Executable),[StringComparison]::OrdinalIgnoreCase)){$same.Dispose();throw 'FOREIGN_PROCESS'}
  try{$same.Kill();if(-not$same.WaitForExit(5000)){throw 'OWNED_PROCESS_BUSY'}}catch{$same.Dispose();throw 'OWNED_PROCESS_BUSY'};$same.Dispose()
}
function Restore-LastGood($C,$I){if($null-eq$I.Active){foreach($n in @('active-candidate.txt','rollback-candidate.txt')){$p=Join-Path $C.Product $n;if(Test-Path -LiteralPath $p){Remove-Item -LiteralPath $p -Force}};return};if((Candidate $C.Product $I.Active $C.Fixture)-cne'HEALTHY'){return};[IO.File]::WriteAllText((Join-Path $C.Product 'active-candidate.txt'),($I.Active+"`n"),[Text.Encoding]::ASCII);$rp=Join-Path $C.Product 'rollback-candidate.txt';if($null-ne$I.RollbackId-and(Candidate $C.Product $I.RollbackId $C.Fixture)-ceq'HEALTHY'){[IO.File]::WriteAllText($rp,($I.RollbackId+"`n"),[Text.Encoding]::ASCII)}elseif(Test-Path -LiteralPath $rp){Remove-Item -LiteralPath $rp -Force}}
function Fixture-Setup($C,$B,$I){$mode='SUCCESS';$mp=Join-Path $C.Root 'fixture-operation.txt';if(Test-Path -LiteralPath $mp){$mode=(Get-Content -Raw -LiteralPath $mp).Trim()};if(@('SUCCESS','FAIL_BEFORE_MARKERS','FAIL_AFTER_STAGE','FAIL_AFTER_MARKER','LOCKED')-cnotcontains$mode){throw 'FIXTURE_INVALID'};$cp=Join-Path $C.Root 'setup-invocations.txt';$n=0;if(Test-Path -LiteralPath $cp){$n=[int](Get-Content -Raw -LiteralPath $cp).Trim()};[IO.File]::WriteAllText($cp,([string]($n+1)+"`n"),[Text.Encoding]::ASCII);if($mode-ceq'LOCKED'){throw 'OWNED_PROCESS_BUSY'};if($mode-ceq'FAIL_BEFORE_MARKERS'){throw 'INSTALLER_FAILED'};$src=Join-Path $C.Root 'fixture-candidate';$dst=Join-Path (Join-Path $C.Product 'versions')$B.CandidateId;if(-not(Test-Path -LiteralPath $src -PathType Container)){throw 'FIXTURE_INVALID'};[IO.Directory]::CreateDirectory((Split-Path -Parent $dst))|Out-Null;if(Test-Path -LiteralPath $dst){Remove-Item -LiteralPath $dst -Recurse -Force};Copy-Item -LiteralPath $src -Destination $dst -Recurse;if($mode-ceq'FAIL_AFTER_STAGE'){throw 'INSTALLER_FAILED'};[IO.Directory]::CreateDirectory($C.Product)|Out-Null;if($null-ne$I.Active-and$I.Active-cne$B.CandidateId){[IO.File]::WriteAllText((Join-Path $C.Product 'rollback-candidate.txt'),($I.Active+"`n"),[Text.Encoding]::ASCII)};[IO.File]::WriteAllText((Join-Path $C.Product 'active-candidate.txt'),($B.CandidateId+"`n"),[Text.Encoding]::ASCII);if($mode-ceq'FAIL_AFTER_MARKER'){throw 'INSTALLER_FAILED'};[IO.File]::WriteAllText((Join-Path $C.Root 'process-state.txt'),"NONE`n",[Text.Encoding]::ASCII)}
function Setup-Once($C,$B,$I){if($C.Fixture){Fixture-Setup $C $B $I;return};$p=Start-Process -FilePath $B.Setup -ArgumentList @('/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART','/ACCEPTDEFAULTS=1','/OPENAFTERINSTALL=0','/PLANAUTOSTART=1','/LANG=english') -WorkingDirectory $C.Bundle -Wait -PassThru;if($p.ExitCode-ne0){throw 'INSTALLER_FAILED'}}
function Launch-Once($C,$I){
  if($C.Fixture){$mode='SUCCESS';$mp=Join-Path $C.Root 'launch-mode.txt';if(Test-Path -LiteralPath $mp){$mode=(Get-Content -Raw -LiteralPath $mp).Trim()};if(@('SUCCESS','FAIL','UNOBSERVED','FOREIGN')-cnotcontains$mode){throw 'FIXTURE_INVALID'};$cp=Join-Path $C.Root 'launch-invocations.txt';$n=0;if(Test-Path -LiteralPath $cp){$n=[int](Get-Content -Raw -LiteralPath $cp).Trim()};[IO.File]::WriteAllText($cp,([string]($n+1)+"`n"),[Text.Encoding]::ASCII);if($mode-ceq'FAIL'){throw 'LAUNCH_FAILED'};if($mode-ceq'UNOBSERVED'){throw 'LAUNCH_NOT_OBSERVED'};if($mode-ceq'FOREIGN'){throw 'FOREIGN_PROCESS'};[IO.File]::WriteAllText((Join-Path $C.Root 'process-state.txt'),"OWNED`n",[Text.Encoding]::ASCII);return}
  $launched=Start-Process -FilePath $I.Executable -WorkingDirectory (Split-Path -Parent $I.Executable) -PassThru
  for($attempt=0;$attempt-lt50;$attempt++){try{$observed=[Diagnostics.Process]::GetProcessById($launched.Id);$path=$observed.MainModule.FileName;if(-not[IO.Path]::GetFullPath($path).Equals([IO.Path]::GetFullPath($I.Executable),[StringComparison]::OrdinalIgnoreCase)){throw 'FOREIGN_PROCESS'};$observed.Dispose();return}catch{if([string]$_.Exception.Message-ceq'FOREIGN_PROCESS'){throw};Start-Sleep -Milliseconds 100}}
  throw 'LAUNCH_NOT_OBSERVED'
}
if(@($args).Count -gt 0 -and @('Auto','Status','Install','Repair') -ccontains [string]$args[0]){$script:Result.action=[string]$args[0]}
try{$p=Parse-Args $args;$script:Result.action=$p.Action;$c=Context;$b=Bundle $c;$script:Result.trust='UNSIGNED_UNTRUSTED';$script:Result.candidateId=$b.CandidateId;$script:Result.setupSha256=$b.SetupSha256;$script:Result.helperSha256=$b.HelperSha256;$script:Result.acceptance=$b.CandidateId+':'+$b.SetupSha256+':'+$b.HelperSha256;$i=Installed $c;$script:Result.installedState=$i.State;$script:Result.rollbackState=$i.Rollback;$r=Recommend $p.Action $i $b.CandidateId;$script:Result.recommended=$r;if($i.Rollback-ceq'UNSAFE'){Fail 'ROLLBACK_UNSAFE' 10};if($p.Action-ceq'Status'-or$r-ceq'NONE'){Complete-Result 'OK' 'READY' 0};if($p.Acceptance-cne$script:Result.acceptance){Fail 'EXACT_ACCEPTANCE_REQUIRED' 10};$name=if($c.Fixture){'Local\AILimitsWidget-Agent-Fixture-v1'}else{'Local\AILimitsWidget-Agent-Maintenance-v1'};$created=$false;$mutex=New-Object Threading.Mutex($false,$name,[ref]$created);if(-not$mutex.WaitOne(0)){$mutex.Dispose();throw 'MAINTENANCE_BUSY'};try{if($r-ceq'LAUNCH'){Launch-Once $c $i;$script:Result.performed='LAUNCH';$script:Result.changed=$true;$script:Result.launched=$true}else{Stop-OwnedOnce $c $i;try{Setup-Once $c $b $i;$script:Result.performed=$r;$script:Result.changed=$true;$after=Installed $c;if($after.Active-cne$b.CandidateId-or$after.State-cne'HEALTHY_STOPPED'){throw 'POSTVERIFY_FAILED'};Launch-Once $c $after;$running=Installed $c;if($running.Active-cne$b.CandidateId-or$running.State-cne'HEALTHY_RUNNING'){throw 'LAUNCH_NOT_OBSERVED'};$script:Result.installedState=$running.State;$script:Result.rollbackState=$running.Rollback;$script:Result.launched=$true}catch{Restore-LastGood $c $i;throw}}}finally{try{$mutex.ReleaseMutex()}catch{};$mutex.Dispose()};Complete-Result 'OK' 'READY' 0}catch{$code=[string]$_.Exception.Message;if(@('EXACT_ACCEPTANCE_REQUIRED','USE_REPAIR','NOT_INSTALLED','MAINTENANCE_BUSY','FOREIGN_PROCESS','FOREIGN_SHORTCUT','ROLLBACK_UNSAFE','OWNED_PROCESS_BUSY')-ccontains$code){Fail $code 10};if(@('INVALID_ARGUMENTS','INVALID_ACTION','INVALID_ACCEPTANCE','PATH_UNSAFE','FIXTURE_INVALID','HELPER_LOCATION_INVALID','BUNDLE_INVALID','MANIFEST_INVALID','SIGNED_PATH_UNSUPPORTED','CHECKSUMS_INVALID','ARTIFACT_MISMATCH','INSTALLED_STATE_UNSAFE','MARKER_INVALID','CANDIDATE_UNSAFE','ENVIRONMENT_UNAVAILABLE')-ccontains$code){Fail $code 20};if(@('INSTALLER_FAILED','POSTVERIFY_FAILED','LAUNCH_FAILED','LAUNCH_NOT_OBSERVED')-ccontains$code){Fail $code 30};Fail 'INTERNAL_FAILURE' 30}
