from __future__ import annotations

STRINGS: dict[str, dict[str, str]] = {
    "uk": {
        "app_name": "LimitHalo",
        "settings_title": "Налаштування",
        "configure": "Налаштувати",
        "setup_intro": "Оберіть лише те, чим користуєтесь. Вимкнені сервіси не займають місце у віджеті.",
        "claude_access": "Дозволити читання лише лімітів Claude",
        "claude_access_revoke": "Доступ до лімітів Claude (зніміть, щоб відкликати)",
        "show_claude": "Показувати Claude автоматично",
        "show_codex": "Показувати Codex автоматично",
        "no_providers_detected": "Підтримувані клієнти ще не знайдені. LimitHalo перевірятиме їх автоматично.",
        "setup_saved": "Налаштування збережено",
        "setup_failed": "Не вдалося застосувати налаштування. Спробуйте ще раз або відкрийте допомогу з відновлення.",
        "settings_preserved": "Файл налаштувань недоступний або пошкоджений. Його не змінено. Відновіть доступ до справного файлу або його резервну копію й перезапустіть віджет. До цього позиція зберігається лише до закриття.",
        "privacy_title": "Приватність і безпека",
        "diagnostics_title": "Безпечна діагностика",
        "refresh": "Оновити",
        "refresh_now": "Оновити зараз",
        "providers": "Провайдери",
        "claude": "Claude",
        "codex": "Codex",
        "provider_auto": "Авто",
        "provider_enabled": "Використовувати",
        "provider_disabled": "Не показувати",
        "provider_detected": "Клієнт знайдено",
        "provider_absent": "Клієнт не знайдено",
        "view": "Вигляд",
        "colors": "Кольори",
        "monochrome": "Монохромні",
        "status_colors": "За станом",
        "notifications": "Сповіщення",
        "notifications_enabled": "Увімкнені",
        "low_quota_alerts": "Сповіщати про малий залишок",
        "alert_threshold": "Поріг залишку",
        "threshold_20": "Поріг 20%",
        "threshold_10": "Поріг 10%",
        "threshold_5": "Поріг 5%",
        "quiet_hours": "Тихі години",
        "quiet_from": "Від",
        "quiet_to": "До",
        "check_updates": "Перевірити оновлення",
        "update_checking": "Перевіряємо оновлення…",
        "update_downloading": "Завантажуємо й перевіряємо…",
        "update_installing": "Встановлюємо оновлення…",
        "update_available_menu": "Завантажити {version}…",
        "update_download_question": "Доступна {version}. Завантажити й перевірити випуск із GitHub?\n\nВіджет продовжить працювати. Встановлення потребує окремого підтвердження.",
        "update_portable_notice": "Це портативна версія. Архів потрібно розпакувати в нову папку вручну; автоматичного встановлення не буде.",
        "update_portable_ready": "Файли перевірені й збережені:\n{folder}\n\nЗакрийте старий віджет, розпакуйте Windows-x64.zip у нову папку та запустіть його. Не запускайте дві версії одночасно.",
        "update_failed": "Не вдалося перевірити або підготувати оновлення. Віджет не змінено. Перевірте з’єднання та за потреби повторіть через меню.",
        "update_current": "У вас актуальний доступний випуск: {version}.",
        "update_install_title": "Встановити оновлення?",
        "update_exact_consent": "Встановити {version} і перезапустити віджет?\n\nФайли відповідають випуску GitHub, але ця бета НЕ має цифрового підпису видавця. Хеші не підтверджують особу видавця. Встановлюйте лише якщо довіряєте DenisShumilov/LimitHalo.\n\nТочний ідентифікатор, який ви підтверджуєте:\n{acceptance}\n\nНалаштування зберігаються. Натискаючи «Так», ви дозволяєте встановити саме ці файли.",
        "updates_not_configured": "Онлайн-оновлення ще не налаштовані для цієї версії. Щоб оновити віджет, запустіть помічник з нового випуску LimitHalo. Ваші налаштування збережуться.",
        "check_updates_disabled": "Оновлення · ще не доступні",
        "update_confirmation": "Оновлення доступне. Виконаємо його тепер? \n\nПрийміть точне значення acceptance:\n{acceptance}",
        "update_started": "Запускаю оновлення з використанням офлайн-скрипта.",
        "update_completed": "Запит прийнято. Оновлення виконується в автоматичному режимі.",
        "privacy_about": "Приватність / Про програму",
        "help": "Допомога",
        "fix_with_ai": "Скопіювати звіт для ремонту через ШІ",
        "repair_help": "Для відновлення файлів програми передайте безпечний звіт своєму кодер-агенту: LimitHalo-Agent.ps1 Status, потім Auto або Repair лише після вашого підтвердження. Це не відновлює пошкоджені налаштування: власник має повернути доступ до справного файлу або відновити його резервну копію й перезапустити віджет. Не передавайте вміст налаштувань, паролі чи токени.",
        "repair_report_copied": "Безпечний звіт скопійовано",
        "advanced": "Додатково",
        "keep_wide": "Зберегти широкий режим",
        "sign_in": "Увійти",
        "connect": "Підкл.",
        "setup": "Налашт.",
        "retry": "Ще раз",
        "update_unavailable": "Оновлення зараз недоступне",
        "auth_client_unavailable": "Офіційний клієнт не знайдено",
        "refreshing": "Оновлюємо…",
        "last_updated": "Оновлено",
        "authorization_required": "Потрібна повторна авторизація",
        "authorization_short": "вхід",
        "offline": "Немає зв’язку — показано останні дані",
        "offline_short": "офлайн",
        "provider_error_short": "не оновлено",
        "window_not_provided_short": "не надано",
        "claude_disabled": "Claude вимкнено",
        "off_value": "Вимк.",
        "claude_consent_title": "Підключити ліміти Claude?",
        "claude_consent_body": "LimitHalo може показувати ліміти Claude. Claude лишається вимкненим, доки ви самі не ввімкнете його.",
        "claude_disclosure_title": "Що саме буде доступно?",
        "claude_disclosure_body": "Програма читає лише розділ claudeAiOauth у %USERPROFILE%/.claude/.credentials.json. Для лімітів вона звертається лише до api.anthropic.com/api/oauth/usage, а для оновлення токена — до platform.claude.com/v1/oauth/token. За потреби лише цей розділ атомарно замінюється під блокуванням .storage-write.lock; усі інші байти файла зберігаються. Чати, дані браузера й логи не читаються, телеметрія не надсилається. Це неофіційна приватна інтеграція для особистого використання; зміни Claude можуть її зламати.",
        "claude_enable": "Увімкнути Claude",
        "claude_off": "Поки без Claude",
        "continue": "Продовжити",
        "language": "Мова",
        "ukrainian": "Українська",
        "english": "English",
        "topmost": "Поверх інших вікон",
        "startup": "Запускати разом із Windows",
        "display": "Вигляд",
        "compact": "Компактний · 364 × 84",
        "wide": "Широкий · 436 × 84",
        "warning_thresholds": "Кольорові пороги залишку (%)",
        "reset_position": "Скинути позицію",
        "save": "Зберегти",
        "cancel": "Скасувати",
        "privacy": "Приватність",
        "security": "Безпека",
        "license": "Ліцензія",
        "copy_version": "Копіювати версію",
        "copy_diagnostics": "Копіювати безпечну діагностику",
        "close": "Закрити",
        "exit": "Вийти",
        "updated_now": "щойно",
        "updated_minutes": "{count} хв тому",
        "privacy_text": "Дані лімітів залишаються в пам’яті й не зберігаються на диску. Програма не читає чати, браузерні дані чи логи та не надсилає телеметрію.",
        "security_text": "Codex запускається лише після перевірки офіційного пакета, підпису та протоколу. Claude запускається лише після вашої явної згоди й працює через окремий обмежений брокер.",
        "license_text": "LimitHalo — спільнотний проєкт під ліцензією MIT. Назви й знаки OpenAI, Codex, Anthropic та Claude належать їхнім власникам; афіліації немає.",
    },
    "en": {
        "app_name": "LimitHalo",
        "settings_title": "Settings",
        "configure": "Configure",
        "setup_intro": "Choose only what you use. Disabled services take no space in the widget.",
        "claude_access": "Allow access to Claude quota values only",
        "claude_access_revoke": "Claude quota access (clear to revoke)",
        "show_claude": "Show Claude automatically",
        "show_codex": "Show Codex automatically",
        "no_providers_detected": "No supported client is detected yet. LimitHalo will keep checking automatically.",
        "setup_saved": "Settings saved",
        "setup_failed": "Settings could not be applied. Try again or open the repair help.",
        "settings_preserved": "The settings file is unavailable or invalid and was left untouched. Restore access to a valid file or restore its valid backup, then restart the widget. Until then, the position lasts only for this session.",
        "privacy_title": "Privacy and security",
        "diagnostics_title": "Safe diagnostics",
        "refresh": "Refresh",
        "refresh_now": "Refresh now",
        "providers": "Providers",
        "claude": "Claude",
        "codex": "Codex",
        "provider_auto": "Auto",
        "provider_enabled": "Use",
        "provider_disabled": "Hide",
        "provider_detected": "Client detected",
        "provider_absent": "Client not detected",
        "view": "View",
        "colors": "Colors",
        "monochrome": "Monochrome",
        "status_colors": "Status colors",
        "notifications": "Notifications",
        "notifications_enabled": "Enabled",
        "low_quota_alerts": "Notify when quota is low",
        "alert_threshold": "Remaining threshold",
        "threshold_20": "Threshold 20%",
        "threshold_10": "Threshold 10%",
        "threshold_5": "Threshold 5%",
        "quiet_hours": "Quiet hours",
        "quiet_from": "From",
        "quiet_to": "To",
        "check_updates": "Check for updates",
        "update_checking": "Checking for updates…",
        "update_downloading": "Downloading and verifying…",
        "update_installing": "Installing update…",
        "update_available_menu": "Download {version}…",
        "update_download_question": "{version} is available. Download and verify the GitHub release?\n\nYour widget keeps running. Installation needs a separate confirmation.",
        "update_portable_notice": "This is a portable copy. You will extract the archive into a new folder yourself; no automatic installation will run.",
        "update_portable_ready": "Verified files saved to:\n{folder}\n\nClose the old widget, extract Windows-x64.zip into a new folder and launch it. Do not run two versions at once.",
        "update_failed": "The update could not be checked or prepared. Your widget was not changed. Check your connection and use the menu to try again if needed.",
        "update_current": "You have the current available release: {version}.",
        "update_install_title": "Install update?",
        "update_exact_consent": "Install {version} and restart the widget?\n\nFiles match the GitHub release, but this beta has NO publisher digital signature. Checksums do not authenticate the publisher. Continue only if you trust DenisShumilov/LimitHalo.\n\nExact release identity you are approving:\n{acceptance}\n\nYour settings are preserved. Choosing Yes authorizes installation of these exact files.",
        "updates_not_configured": "Online updates are not configured for this version yet. To update the widget, run the helper from a newer LimitHalo release. Your settings will be preserved.",
        "check_updates_disabled": "Updates · not available yet",
        "update_confirmation": "An update is available. Continue to install it now?\n\nAccept the exact value:\n{acceptance}",
        "update_started": "Running the offline update script now.",
        "update_completed": "Request accepted. Update is running automatically.",
        "privacy_about": "Privacy / About",
        "help": "Help",
        "fix_with_ai": "Copy report for AI repair",
        "repair_help": "To repair program files, give the safe report to your coding agent: LimitHalo-Agent.ps1 Status, then Auto or Repair only after your approval. This does not restore invalid settings: the owner must restore access to a valid settings file or restore its valid backup, then restart the widget. Never share settings contents, passwords or tokens.",
        "repair_report_copied": "Safe report copied",
        "advanced": "Advanced",
        "keep_wide": "Keep wide layout",
        "sign_in": "Sign in",
        "connect": "Connect",
        "setup": "Set up",
        "retry": "Retry",
        "update_unavailable": "Updates are currently unavailable",
        "auth_client_unavailable": "Official client not found",
        "refreshing": "Refreshing…",
        "last_updated": "Updated",
        "authorization_required": "Reauthorization required",
        "authorization_short": "auth",
        "offline": "Offline — showing last known data",
        "offline_short": "offline",
        "provider_error_short": "not updated",
        "window_not_provided_short": "not provided",
        "claude_disabled": "Claude is off",
        "off_value": "Off",
        "claude_consent_title": "Connect Claude limits?",
        "claude_consent_body": "LimitHalo can show Claude limits. Claude stays off until you explicitly enable it.",
        "claude_disclosure_title": "What exactly is accessed?",
        "claude_disclosure_body": "The app reads only the claudeAiOauth section in %USERPROFILE%/.claude/.credentials.json. It uses only api.anthropic.com/api/oauth/usage for limits and platform.claude.com/v1/oauth/token for token refresh. When required, only that section is atomically replaced under .storage-write.lock while every unrelated file byte is preserved. Chats, browser data, and logs are never read, and no telemetry is sent. This is an unsupported private integration for personal use and may stop working when Claude changes it.",
        "claude_enable": "Enable Claude",
        "claude_off": "Keep Claude off",
        "continue": "Continue",
        "language": "Language",
        "ukrainian": "Українська",
        "english": "English",
        "topmost": "Always on top",
        "startup": "Start with Windows",
        "display": "Display",
        "compact": "Compact · 364 × 84",
        "wide": "Wide · 436 × 84",
        "warning_thresholds": "Remaining-color thresholds (%)",
        "reset_position": "Reset position",
        "save": "Save",
        "cancel": "Cancel",
        "privacy": "Privacy",
        "security": "Security",
        "license": "License",
        "copy_version": "Copy version",
        "copy_diagnostics": "Copy safe diagnostics",
        "close": "Close",
        "exit": "Exit",
        "updated_now": "just now",
        "updated_minutes": "{count} min ago",
        "privacy_text": "Limit values stay in memory and are not cached on disk. The app reads no chats, browser data, or logs and sends no telemetry.",
        "security_text": "Codex starts only after official-package, signer, and protocol checks. Claude starts only after explicit consent and runs through a separate constrained broker.",
        "license_text": "LimitHalo is a community MIT-licensed project. OpenAI, Codex, Anthropic, and Claude names and marks belong to their owners; no affiliation is claimed.",
    },
}


def tr(language: str, key: str, **values: object) -> str:
    try:
        value = STRINGS[language][key]
    except KeyError as exc:
        raise KeyError(f"missing translation: {language}.{key}") from exc
    return value.format(**values)


def assert_translation_parity() -> None:
    if set(STRINGS) != {"uk", "en"} or set(STRINGS["uk"]) != set(STRINGS["en"]):
        raise ValueError("translation catalogs differ")
    if any(not value.strip() for catalog in STRINGS.values() for value in catalog.values()):
        raise ValueError("empty translation")
