from __future__ import annotations

import ast
import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BROKER = ROOT / "native" / "claude_broker"
EXPECTED_BROKER_SHA256 = {
    "broker_core.cpp": "aef9181d07080a1118eeb5c033491f2a4ec142382cacb67ac6d922ab4efc2f12",
    "broker_core.h": "b3702412c0c6864f6964951fff9c43e159773421f994a179c810c40257925975",
    "production_adapter.cpp": "0cb2f1333b723ccc9293e6876089a30b590309f9422b69339a76a7a59fb42b6b",
    "production_adapter.h": "a271566c93afa24b81655154084aec92fdbb732322a4413b63d68828236cdb68",
    "production_main.cpp": "615a41121528651d087fe1af2a799986dd6b6a0f28465d82841cb65decd2dabb",
    "synthetic_main.cpp": "3b7f11ca97f8f450169e7ee76c8b185f778632046594f2597b38505b25628392",
}
FORBIDDEN_NATIVE_FRAGMENTS = (
    "AIUsageWidgetBrowserless",
    "auth-lock.json",
    "LoadAuthLock",
    "StoreAuthLock",
    "ClearAuthLock",
    "RegOpenKey",
    "RegQueryValue",
    "Volatile Environment",
    "User Shell Folders",
    "LocalDumps",
    "AeDebug",
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    forbidden_generated = [
        path.relative_to(ROOT).as_posix()
        for path in ROOT.rglob("*")
        if path.name == "__pycache__" or path.suffix.casefold() in {".pyc", ".pyo"}
    ]
    if forbidden_generated:
        raise AssertionError(f"generated bytecode is forbidden: {sorted(forbidden_generated)}")
    python_files = sorted(ROOT.rglob("*.py"), key=lambda path: path.relative_to(ROOT).as_posix())
    parsed = 0
    for path in python_files:
        ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        parsed += 1
    broker_files = sorted(BROKER.iterdir(), key=lambda path: path.name)
    if {path.name for path in broker_files} != set(EXPECTED_BROKER_SHA256) or any(not path.is_file() for path in broker_files):
        raise AssertionError("native broker file set changed")
    broker_matches = 0
    for path in broker_files:
        if sha256(path) != EXPECTED_BROKER_SHA256[path.name]:
            raise AssertionError(f"native broker lineage mismatch: {path.name}")
        broker_matches += 1
    native_text = "\n".join(path.read_text(encoding="utf-8") for path in broker_files)
    found_native = sorted(fragment for fragment in FORBIDDEN_NATIVE_FRAGMENTS if fragment in native_text)
    if found_native:
        raise AssertionError(f"forbidden native persistence or registry capability: {found_native}")
    if "bool authSuppressed = false;" not in native_text:
        raise AssertionError("process-memory-only Claude auth suppression is missing")
    demo = ast.parse((ROOT / "src" / "limit_halo" / "demo.py").read_text(encoding="utf-8"))
    demo_imports: set[str] = set()
    for node in ast.walk(demo):
        if isinstance(node, ast.Import):
            demo_imports.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            demo_imports.add(node.module or "")
    forbidden = {
        "subprocess", "socket", "limit_halo.app", "limit_halo.codex_protocol",
        "limit_halo.codex_discovery", "limit_halo.claude_protocol", "limit_halo.process_guard",
    }
    if demo_imports & forbidden:
        raise AssertionError(f"fixture demo imports production capability: {sorted(demo_imports & forbidden)}")
    result = {
        "schemaVersion": "1.0.0",
        "pythonSyntaxFiles": parsed,
        "frozenSuccessorBrokerFiles": broker_matches,
        "forbiddenNativeCapabilities": 0,
        "fixtureDemoProductionCapabilityImports": 0,
        "status": "PASS",
    }
    print(json.dumps(result, ensure_ascii=True, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
